//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciDart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdPreciDartEntities1 : DbContext
    {
        public bdPreciDartEntities1()
            : base("name=bdPreciDartEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblEquipe> tblEquipes { get; set; }
        public DbSet<tblJoueur> tblJoueurs { get; set; }
        public DbSet<tblMatch> tblMatches { get; set; }
        public DbSet<tblScore> tblScores { get; set; }
    }
}
