//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciDart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipe
    {
        public tblEquipe()
        {
            this.tblJoueurs = new HashSet<tblJoueur>();
        }
    
        public int IdEquipe { get; set; }
        public string NomEquipe { get; set; }
    
        public virtual ICollection<tblJoueur> tblJoueurs { get; set; }
    }
}
