//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciDart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJoueur
    {
        public tblJoueur()
        {
            this.tblMatches1 = new HashSet<tblMatch>();
            this.tblMatches2 = new HashSet<tblMatch>();
            this.tblScores = new HashSet<tblScore>();
        }
    
        public short NoJoueur { get; set; }
        public string NomJoueur { get; set; }
        public Nullable<int> NoEquipe { get; set; }
    
        public virtual tblEquipe tblEquipe { get; set; }
        public virtual ICollection<tblMatch> tblMatches1 { get; set; }
        public virtual ICollection<tblMatch> tblMatches2 { get; set; }
        public virtual ICollection<tblScore> tblScores { get; set; }
    }
}
