//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciDart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatch
    {
        public tblMatch()
        {
            this.tblScores = new HashSet<tblScore>();
        }
    
        public int IdMatch { get; set; }
        public short NoJoueur1 { get; set; }
        public short NoJoueur2 { get; set; }
        public System.DateTime DateMatch { get; set; }
    
        public virtual tblJoueur tblJoueur1 { get; set; }
        public virtual tblJoueur tblJoueur2 { get; set; }
        public virtual ICollection<tblScore> tblScores { get; set; }
    }
}
