//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciDart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScore
    {
        public int IdScore { get; set; }
        public byte Tour { get; set; }
        public short Score { get; set; }
        public int IdMatch { get; set; }
        public short IdJoueur { get; set; }
    
        public virtual tblJoueur tblJoueur { get; set; }
        public virtual tblMatch tblMatch { get; set; }
    }
}
